stages:
  - build
  - deploy

build:
  stage: build
  image: node:latest
  script:
    - echo "Building the app"
    - CI=false npm install
    - CI=false npm run build
  artifacts:
    name: react-build
    paths:
      - build
  only:
    - main    

publish:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - echo "Building the app"
    # - aws s3 cp ./build/ $AWS_S3_BUCKET_URL --recursive --include "*"
    - aws s3 sync ./build $AWS_S3_BUCKET_URL --delete
  only:
    - main